apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: b4z9111bj-nodejs 
  janus-idp.io/tekton: b4z9111bj-nodejs
  backstage.io/kubernetes-id: b4z9111bj-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: b4z9111bj-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml