apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: b4z9111bj-nodejs
  janus-idp.io/tekton: b4z9111bj-nodejs
  backstage.io/kubernetes-id: b4z9111bj-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: b4z9111bj-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
